<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3locations"
 *
 * Auto generated by Extension Builder 2014-11-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['t3locations'] = array(
	'title' => 'Location Tools',
	'description' => 'Provides you with various tools for displaying/managing your customers locations.',
	'category' => 'plugin',
	'author' => 'Sebastian Iffland',
	'author_email' => 'Sebastian.Iffland@ecom-ex.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'php' => '5.4.0-5.5.99'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);